services:
  structurizr:
    image: structurizr/lite:latest
    volumes:
      - ./docs:/usr/local/structurizr
    ports:
        - "8080:8080"
  app:
    build: ./app
    env_file:
      - ./app/.env
      - ./app/.env.development.local
    ports:
      - "3000:3000"
